// Actions
export const SESSION_LOAD_DB = 'SESSION_LOAD_DB';
export const SESSION_GENERATE_ACCOUNT = 'SESSION_GENERATE_ACCOUNT';
export const SESSION_RECOVER_ACCOUNT = 'SESSION_RECOVER_ACCOUNT';

export const PROCUREMENT_GET_TENDERS = 'PROCUREMENT_GET_TENDERS';
export const PROCUREMENT_CREATE_TENDER = 'PROCUREMENT_CREATE_TENDER';

export const TENDER_INIT = 'TENDER_INIT';
export const TENDER_GET_BIDDING_PERIOD = 'TENDER_GET_BIDDING_PERIOD';
export const TENDER_GET_TENDER_DESCRIPTION = 'TENDER_GET_TENDER_DESCRIPTION';
export const TENDER_CREATE_BID = 'TENDER_CREATE_BID';
export const TENDER_GET_BIDS = 'TENDER_GET_BIDS';
export const TENDER_SEND_MESSAGE = 'TENDER_SEND_MESSAGE';
export const TENDER_GET_MESSAGES = 'TENDER_GET_MESSAGES';
export const TENDER_GET_OBSERVATIONS = 'TENDER_GET_OBSERVATIONS';
export const TENDER_GET_WINNER_OBSERVATIONS = 'TENDER_GET_WINNER_OBSERVATIONS';
export const TENDER_GET_WINNER = 'TENDER_GET_WINNER';
export const TENDER_SUBMIT_OBSERVATION = 'TENDER_SUBMIT_OBSERVATION';
export const TENDER_SUBMIT_WINNER_OBSERVATION = 'TENDER_SUBMIT_WINNER_OBSERVATION';
export const TENDER_START_AUCTION = 'TENDER_START_AUCTION';

export const BID_INIT = 'BID_INIT';
export const BID_GET_OBSERVATIONS = 'BID_GET_OBSERVATIONS';
export const BID_GET_SCORE_OBSERVATIONS = 'BID_GET_SCORE_OBSERVATIONS';
export const BID_SUBMIT_OBSERVATION = 'BID_SUBMIT_OBSERVATION';
export const BID_SUBMIT_SCORE_OBSERVATION = 'BID_SUBMIT_SCORE_OBSERVATION';


// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';

export const PROCUREMENT_SET_PROPERTY = 'PROCUREMENT_SET_PROPERTY';

export const TENDER_SET_PROPERTY = 'TENDER_SET_PROPERTY';

export const BID_SET_PROPERTY = 'BID_SET_PROPERTY';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';

export const TENDER_GET_IS_EMPTY_BIDS = 'TENDER_GET_IS_EMPTY_BIDS';
export const TENDER_GET_IS_WINNER_SET = 'TENDER_GET_IS_WINNER_SET';
