// Actions
export const SESSION_GENERATE_ACCOUNT = 'SESSION_GENERATE_ACCOUNT';

export const PROCUREMENT_GET_TENDERS = 'PROCUREMENT_GET_TENDERS';

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';

export const PROCUREMENT_SET_PROPERTY = 'PROCUREMENT_SET_PROPERTY';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';
