export default [
  { code: 'NXTWY.UMT.3', text: 'Unidad (UN)' },
  { code: 'NXTWY.UMT.30', text: 'Kilogramo (KG)' },
  { code: 'NXTWY.UMT.31', text: 'Kilometro (KM)' },
  { code: 'NXTWY.UMT.32', text: 'Litro (L)' },
  { code: 'NXTWY.UMT.36', text: 'Metro (M)' },
  { code: 'NXTWY.UMT.40', text: 'Milimetro (MM)' },
  { code: 'NXTWY.UMT.46', text: 'Pulgada (POL)' },
  { code: 'NXTWY.UMT.47', text: 'Rollo (ROL)' },
  { code: 'NXTWY.UMT.48', text: 'Bolsa (SC)' },
  { code: 'NXTWY.UMT.50', text: 'Tonelada (TON)' },
  { code: 'NXTWY.UMT.9', text: 'Caja (CX)' },
  { code: 'NXTWY.UMT.61', text: 'Centímetro Cuadrado (CM2)' },
  { code: 'NXTWY.UMT.72', text: 'Gramos /metro cúbico (GM3)' },
  { code: 'NXTWY.UMT.96', text: 'Libra US (LB)' },
  { code: 'NXTWY.UMT.157', text: 'Barril (PIP)' },
  { code: 'NXTWY.UMT.100', text: 'Megahertz (MHZ)' },
  { code: 'NXTWY.UMT.101', text: 'Megajoule (MEJ)' },
  { code: 'NXTWY.UMT.102', text: 'Meganewton (MN)' },
  { code: 'NXTWY.UMT.103', text: 'Megapascal (MPA)' },
  { code: 'NXTWY.UMT.104', text: 'Megavatios/Hora (MWH)' },
  { code: 'NXTWY.UMT.107', text: 'Metro bar/Segundo (MBZ)' },
  { code: 'NXTWY.UMT.108', text: 'Metropascal/Segundo (MPZ)' },
  { code: 'NXTWY.UMT.11', text: 'Centímetro (CM)' },
  { code: 'NXTWY.UMT.110', text: 'microamperio (μA)' },
  { code: 'NXTWY.UMT.111', text: 'Microgramos / Litro (μGL)' },
  { code: 'NXTWY.UMT.112', text: 'Microgramos / metro cúbico (μGQ)' },
  { code: 'NXTWY.UMT.113', text: 'Micrómetro (μM)' },
  { code: 'NXTWY.UMT.114', text: 'Microsegundo (MIS)' },
  { code: 'NXTWY.UMT.115', text: 'Mil (MIL)' },
  { code: 'NXTWY.UMT.116', text: 'Milla (MI)' },
  { code: 'NXTWY.UMT.117', text: 'Milla cuadrada (MI2)' },
  { code: 'NXTWY.UMT.118', text: 'Miliamperio (MA)' },
  { code: 'NXTWY.UMT.12', text: 'Cien (CT)' },
  { code: 'NXTWY.UMT.120', text: 'Milligramo (MG)' },
  { code: 'NXTWY.UMT.126', text: 'Milijoule (MIJ)' },
  { code: 'NXTWY.UMT.127', text: 'ml Reactivo (MLW)' },
  { code: 'NXTWY.UMT.128', text: 'Milimetro cuadrado (MM2)' },
  { code: 'NXTWY.UMT.129', text: 'Millimetro/año (MMA)' },
  { code: 'NXTWY.UMT.13', text: 'Conjunto (CNJ)' },
  { code: 'NXTWY.UMT.130', text: 'Millimetro/Hora (MMH)' },
  { code: 'NXTWY.UMT.131', text: 'Millimetro/Segundo (MMS)' },
  { code: 'NXTWY.UMT.132', text: 'Milisegundos (MS)' },
  { code: 'NXTWY.UMT.133', text: 'Militesla (MTE)' },
  { code: 'NXTWY.UMT.136', text: 'Nanometro (NAM)' },
  { code: 'NXTWY.UMT.137', text: 'Nano segundos (NS)' },
  { code: 'NXTWY.UMT.138', text: 'Número de Personas (PRS)' },
  { code: 'NXTWY.UMT.139', text: 'OHM (OHM)' },
  { code: 'NXTWY.UMT.14', text: 'Decímetro (DM)' },
  { code: 'NXTWY.UMT.140', text: 'Onza (OZ)' },
  { code: 'NXTWY.UMT.141', text: 'Presupuesto (ORC)' },
  { code: 'NXTWY.UMT.142', text: 'Paquete (PAC)' },
  { code: 'NXTWY.UMT.143', text: 'Partes por Billón (masa) (MPB)' },
  { code: 'NXTWY.UMT.144', text: 'Partes por Billón (PPB)' },
  { code: 'NXTWY.UMT.145', text: 'Partes por Millón (PPM)' },
  { code: 'NXTWY.UMT.146', text: 'Partes por Millon (masa) (MPM)' },
  { code: 'NXTWY.UMT.148', text: 'Partes por Trillón (volumen) (PAD)' },
  { code: 'NXTWY.UMT.15', text: 'Decímetro Cúbico (DM3)' },
  { code: 'NXTWY.UMT.150', text: 'Partes por Trillón (PPT)' },
  { code: 'NXTWY.UMT.151', text: 'Partes por Trillón (masa) (MPT)' },
  { code: 'NXTWY.UMT.152', text: 'Pascal (PA)' },
  { code: 'NXTWY.UMT.153', text: 'Pie (PÉ)' },
  { code: 'NXTWY.UMT.154', text: 'Pie cuadrado (PÉ2)' },
  { code: 'NXTWY.UMT.156', text: 'Picosegundo (PS)' },
  { code: 'NXTWY.UMT.158', text: 'Pulgada (IN)' },
  { code: 'NXTWY.UMT.159', text: 'Pulgada cuadrada (2IN)' },
  { code: 'NXTWY.UMT.16', text: 'Día (D)' },
  { code: 'NXTWY.UMT.160', text: 'Porcentaje(masa) (M%)' },
  { code: 'NXTWY.UMT.1601', text: 'Pieza (PEÇ)' },
  { code: 'NXTWY.UMT.163', text: 'Kilogramo reactivo (KGR)' },
  { code: 'NXTWY.UMT.164', text: 'Kilogramo/ Decímetro cúbico (KD3)' },
  { code: 'NXTWY.UMT.166', text: 'Kilohertz (KHZ)' },
  { code: 'NXTWY.UMT.167', text: 'Kilojoule (KJ)' },
  { code: 'NXTWY.UMT.17', text: 'Paquete (EMB)' },
  { code: 'NXTWY.UMT.170', text: 'Kilometro cuadrado (KM2)' },
  { code: 'NXTWY.UMT.172', text: 'Kilovatios Hora (KWH)' },
  { code: 'NXTWY.UMT.173', text: 'Contenedor (REC)' },
  { code: 'NXTWY.UMT.174', text: 'Metro/SegundoM/ (S)' },
  { code: 'NXTWY.UMT.175', text: 'Tambor (TAM)' },
  { code: 'NXTWY.UMT.176', text: 'Tesla (TES)' },
  { code: 'NXTWY.UMT.18', text: 'Hoja (FLH)' },
  { code: 'NXTWY.UMT.180', text: 'Unidad de Actividad (UA)' },
  { code: 'NXTWY.UMT.181', text: 'Unidad de Subcontratación (US)' },
  { code: 'NXTWY.UMT.182', text: 'Unidad de Enzima (UE)' },
  { code: 'NXTWY.UMT.183', text: 'Unidades de enzima/ml (EML)' },
  { code: 'NXTWY.UMT.184', text: 'Viga (ViG)' },
  { code: 'NXTWY.UMT.185', text: 'Voltio (V)' },
  { code: 'NXTWY.UMT.19', text: 'Botella (GAR)' },
  { code: 'NXTWY.UMT.2', text: 'Diverso (DIV)' },
  { code: 'NXTWY.UMT.20', text: 'Gramo (G)' },
  { code: 'NXTWY.UMT.21', text: 'Bruto (GRO)' },
  { code: 'NXTWY.UMT.22', text: 'Hora Local (HL)' },
  { code: 'NXTWY.UMT.25', text: 'Juego (JG)' },
  { code: 'NXTWY.UMT.26', text: 'Kilogramo /Metro cúbico (KGM)' },
  { code: 'NXTWY.UMT.27', text: 'KiloVoltios (KV)' },
  { code: 'NXTWY.UMT.28', text: 'Kilo Voltios Amperios (KVA)' },
  { code: 'NXTWY.UMT.29', text: 'Kilo Vatios (KW)' },
  { code: 'NXTWY.UMT.34', text: 'Paquete (MAÇ)' },
  { code: 'NXTWY.UMT.35', text: 'Mes (MES)' },
  { code: 'NXTWY.UMT.37', text: 'Metro cúbico (M3)' },
  { code: 'NXTWY.UMT.38', text: 'Metro Lineal (ML)' },
  { code: 'NXTWY.UMT.39', text: 'Metro cuadrado (M2)' },
  { code: 'NXTWY.UMT.4', text: 'Año (ANO)' },
  { code: 'NXTWY.UMT.41', text: 'Minuto (MIN)' },
  { code: 'NXTWY.UMT.42', text: 'Newton (N)' },
  { code: 'NXTWY.UMT.44', text: 'Paleta (PAL)' },
  { code: 'NXTWY.UMT.45', text: 'Par (PAR)' },
  { code: 'NXTWY.UMT.49', text: 'Semana (SEM)' },
  { code: 'NXTWY.UMT.51', text: 'Valor Global (VG)' },
  { code: 'NXTWY.UMT.53', text: 'Acre (ACR)' },
  { code: 'NXTWY.UMT.54', text: 'Amperio (A)' },
  { code: 'NXTWY.UMT.55', text: 'Arroba (ARR)' },
  { code: 'NXTWY.UMT.56', text: 'Valor Articulo (VAL)' },
  { code: 'NXTWY.UMT.58', text: 'Cada (CDA)' },
  { code: 'NXTWY.UMT.59', text: 'Caja de Cartón (CXC)' },
  { code: 'NXTWY.UMT.6', text: 'Cubo (BLD)' },
  { code: 'NXTWY.UMT.60', text: 'Carga (CAR)' },
  { code: 'NXTWY.UMT.62', text: 'Cono (CON)' },
  { code: 'NXTWY.UMT.63', text: 'Docena (DZ)' },
  { code: 'NXTWY.UMT.64', text: 'Flete (FRT)' },
  { code: 'NXTWY.UMT.66', text: 'Galones por milla (US) (GPM)' },
  { code: 'NXTWY.UMT.67', text: 'Giga joule (GJ)' },
  { code: 'NXTWY.UMT.68', text: 'Hierba de oro (GAU)' },
  { code: 'NXTWY.UMT.69', text: 'Hierba Reactiva (GR)' },
  { code: 'NXTWY.UMT.73', text: 'Gramos/litro (GLI)' },
  { code: 'NXTWY.UMT.75', text: 'Grado (GRA)' },
  { code: 'NXTWY.UMT.76', text: 'Hectárea (HA)' },
  { code: 'NXTWY.UMT.77', text: 'Hertz (1/seg) (HZ)' },
  { code: 'NXTWY.UMT.78', text: 'Hora HombreH/ (H)' },
  { code: 'NXTWY.UMT.79', text: 'Hora orden (HO)' },
  { code: 'NXTWY.UMT.8', text: 'Botija (BT)' },
  { code: 'NXTWY.UMT.80', text: 'Hora cubo (HB)' },
  { code: 'NXTWY.UMT.81', text: 'Martillo/Hora (HM)' },
  { code: 'NXTWY.UMT.82', text: 'Hora Destajo (HR)' },
  { code: 'NXTWY.UMT.83', text: 'Escoba Hora (HV)' },
  { code: 'NXTWY.UMT.86', text: 'Yarda (YD)' },
  { code: 'NXTWY.UMT.88', text: 'Joule (J)' },
  { code: 'NXTWY.UMT.91', text: 'Reactivo kg / kg (KWK)' },
  { code: 'NXTWY.UMT.92', text: 'Kiloamperio (KA)' },
  { code: 'NXTWY.UMT.93', text: 'Kilonewton (KN)' },
  { code: 'NXTWY.UMT.95', text: 'Kilopascals (KPA)' },
  { code: 'NXTWY.UMT.99', text: 'Tapas (GRD)' },
];
